services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: communitylab-n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=${N8N_WEBHOOK_URL:-http://localhost:5678/}
      - NODE_ENV=production
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=24
      - NODE_OPTIONS=--max-old-space-size=512
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=America/Bogota
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
    volumes:
      - n8n_data:/home/node/.n8n
      - ./data:/data:ro


volumes:
  n8n_data:
    external: true
    name: n8n-hackathon_n8n_data


